des <number_small>: user.desktop(number_small)
des right: user.desktop_next()
des left: user.desktop_last()
des show: user.desktop_show()
window move des <number>: user.window_move_desktop(number)
window move des left: user.window_move_desktop_left()
window move des right: user.window_move_desktop_right()
