go desy <number_small>: user.desktop(number_small)
go desy right: user.desktop_next()
go desy left: user.desktop_last()
desy show: user.desktop_show()
#win desy <number>: user.window_move_desktop(number)
win desy left: user.window_move_desktop_left()
win desy right: user.window_move_desktop_right()
